subscription_id: ${{ secrets.AZ_CLIENT_SECRET }}
client_id: ${{ secrets.AZ_CLIENT_ID }}
client_secret: ${{ secrets.AZ_CLIENT_SECRET }}
# tenant_id: ${{ secrets.AZ_TENANT_ID }}
environment: poc
az_region: eus
service: xyz_app
location: "East US"
tags:
  project: XYZ_Exercise
