subcription_id: ${{ AZ_CLIENT_SECRET }}
client_id: ${{ AZ_CLIENT_ID }}
client_secret: ${{ AZ_CLIENT_SECRET }}
tenant_id: ${{ AZ_TENANT_ID }}
environment: poc
az_region: eus
service: xyz_app
location: "East US"
tags:
  project: XYZ_Exercise
