---
apiVersion: v1
kind: Namespace
metadata:
  name: xyz-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: xyz-app-deployment
  labels:
    app: xyz-app-deployment
  namespace: xyz-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: xyz-app
  template:
    metadata:
      labels:
        app: xyz-app
    spec:
      containers:
      - name: xyz-app
        image: xyzappsample.azurecr.io/sample/xyzsample:latest
        ports:
        - containerPort: 3001
        livenessProbe:
          httpGet:
            path: /live
            port: 3001
          initialDelaySeconds: 3
          periodSeconds: 3
          failureThreshold: 2
---
apiVersion: v1
kind: Service
metadata:
  name: xyz-app
  namespace: xyz-app
spec:
  type: LoadBalancer
  ports:
  - port: 3001
  selector:
    app: xyz-app

