name: Terraform Plan & Apply

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform-plan:
    name: Terraform Plan
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup TF
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_wrapper: false
    - name: TF init
      run: terraform init -backend-config="access_key=${{ secrets.AZ_TFSTATE_KEY }}"
    - name: TF validate
      run: terraform validate
    - name: TF format
      run: terraform fmt
    - name: Terraform plan
      run: |
        terraform plan -var="client_secret=${{ secrets.az_client_secret}}" -var="client_id=${{ secrets.az_client_id }}" -out tfplan
    - name: Publish TF Plan
      uses: actions/upload-artifact@v3
      with:
        name: tfplan
        path: tfplan
