name: Terraform Plan & Apply

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform-plan:
    name: Terraform Plan
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup TF
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_wrapper: false
    - name: TF init
      run: terraform init
